services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    networks:
      - jupiterv2

networks:
  jupiterv2:
    ipam:
      driver: default
      config:
        - subnet: 172.8.0.0/16
          ip_range: 172.8.5.0/24
          gateway: 172.8.5.254
