services:
  postgres:
    image: postgres:latest
    env_file:
      - path: .env
        required: false
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-jupiter}"
      POSTGRES_USER: "${POSTGRES_USER:-jupiter}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-jupiter}"
    ports:
      - "${POSTGRES_PORT:-45432}:5432"
    volumes:
      - "${POSTGRES_DATA_DIR:-./.data/postgres}:/var/lib/postgresql/data"

  app:
    profiles: [standalone]
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: "${USERNAME:-${USER}}"
    env_file:
      - path: .env
        required: false
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB:-jupiter}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER:-jupiter}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD:-jupiter}"
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
    labels:
      org.springframework.boot.ignore: "true"
    ports:
      - "${PORT:-7272}:7272"
    volumes:
      - "${HOST_DEVELOPER_DIR:-${HOME}/developer}:${HOST_DEVELOPER_DIR:-${HOME}/developer}"
      - "${HOST_SSH_DIR:-${HOME}/.ssh}:/home/${USERNAME:-${USER}}/.ssh:ro"
